In [1]:
import numpy as np

In [3]:
A = np.matrix([[1, 2], [3, 4]])

In [6]:
B = 5 + A

In [9]:
C = A + B

In [8]:
print(A)
print(B)
print(C)
print('')
print(type(A))
print(type(B))
print(type(C))

[[1 2]
 [3 4]]
[[6 7]
 [8 9]]
[[ 7  9]
 [11 13]]

<class 'numpy.matrix'>
<class 'numpy.matrix'>
<class 'numpy.matrix'>
