In [1]:
import numpy as np
import numpy.linalg as la

**Formalities**

* An orthogonal matrix is one that the dot product of any column by itself is 1, otherwise is 0.
* The product between the transpose of a matrix and the original matrix is equal to the identity matrix. So the inverse of any orthogonal matrix is the tranpose of that matrix.

In [10]:
# a pure rotation in R2 space gives an orthogonal matrix
# note that this is a square matrix
A = np.matrix([[0,-1], [1,0]])
print('Matrix A')
print(A)
print('\nInverse')
print(la.inv(A))
print('\nTranspose')
print(A.T)

Matrix A
[[ 0 -1]
 [ 1  0]]

Inverse
[[ 0.  1.]
 [-1. -0.]]

Transpose
[[ 0  1]
 [-1  0]]


In [11]:
# now, because this is a orthonormal square matrix...
print('AT*A and A*AT:')
print(A.T*A)
print(A*A.T)
print('\nAInv*A and A*AInv')
print(la.inv(A)*A)
print(A*la.inv(A))

AT*A and A*AT:
[[1 0]
 [0 1]]
[[1 0]
 [0 1]]

AInv*A and A*AInv
[[1. 0.]
 [0. 1.]]
[[1. 0.]
 [0. 1.]]


In [15]:
# use qr decomposition, A = Q*R
A = np.matrix([[1,2], [3,4]])
Q, R = la.qr(A)
print('A:')
print(A)
print('\nQ:')
print(Q)
print('\nR:')
print(R)
print('\nQ*R:')
print(Q*R)

A:
[[1 2]
 [3 4]]

Q:
[[-0.31622777 -0.9486833 ]
 [-0.9486833   0.31622777]]

R:
[[-3.16227766 -4.42718872]
 [ 0.         -0.63245553]]

Q*R:
[[1. 2.]
 [3. 4.]]
